import { IncomingJob } from '../types';

const IncomingAllJobs: IncomingJob[] = [
  {
    vehicleRegistrationNumber: 'XYZ789',
    vehicleName: 'Truck Model',
    vehicleType: 'Truck',
    vehicleRegisteredMobileNo: '9876543211',
    customerLatitude: '28.7042',
    customerLongitude: '77.1026',
    customerAddress: '102-B, Phase 2, Tilak Nagar, New Delhi',
    dropLocationLatitude: '28.7042',
    dropLocationLongitude: '77.1026',
    customerName: 'Another Customer',
    customerMobileNumber: '9876543211',
    customerStatus: 'Inactive',
    partnerId: '12346',
    partnerName: 'Another Partner',
    partnerPicture: 'another-url',
    partnerOrgName: 'Another Org',
    partnerAddress: 'Another Partner Address',
    partnerPhoneNumber: '7412059856',
    partnerLatitude: '28.7042',
    partnerLongitude: '77.1026',
    rsaTicketNumber: '123456',
    isEV: false,
    issue: '',
    isTowing: false,
    dropLocation: 'C 45, Nehru Place, Delhi',
  },
  {
    vehicleRegistrationNumber: 'ABC123',
    vehicleName: 'Car Model',
    vehicleType: 'Sedan',
    vehicleRegisteredMobileNo: '9876543210',
    customerLatitude: '28.7041',
    customerLongitude: '77.1025',
    customerAddress: '102-B, Phase 2, Tilak Nagar, New Delhi',
    dropLocationLatitude: '28.7041',
    dropLocationLongitude: '77.1025',
    customerName: 'Customer Name',
    customerMobileNumber: '9876543210',
    customerStatus: 'Active',
    partnerId: '12345',
    partnerName: 'Partner Name',
    partnerPicture: 'url',
    partnerOrgName: 'Org Name',
    partnerAddress: 'Partner Address',
    partnerPhoneNumber: '7412059855',
    partnerLatitude: '28.7041',
    partnerLongitude: '77.1025',
    rsaTicketNumber: '123456',
    isEV: true,
    issue: 'Puncture',
    isTowing: false,
    dropLocation: '',
  },
];

export default IncomingAllJobs;
